@startuml
hide footbox
!pragma teoz true

entity "User" as u

box "E2E Simulator Orchestrator" #LightBlue
participant "Orchestrator\nEngine" as orch
participant "Air Interface\nHandler" as hndl
end box

database "git\nAir Interface\nAnalyzer" as srv

u -> orch: run -i /input/scenario.yml
activate orch
orch -> orch: parse(scenario)
...
orch -> hndl: run Air Interface Analyzer
activate hndl
hndl -> srv: POST: airinterfaceRequest
activate srv
hndl <- srv: airinterfaceData
deactivate srv
hndl -> hndl: parse(airinterfaceData)
hndl -> orch: airinterfaceData
deactivate hndl
...
orch -> orch: post-process


@enduml